app/urls.py
from lib.helpers.routing import get_class_view, get_view

urlpatterns = [
    get_view("signup"),
    get_view("create_website"),
    get_class_view("create_advertisement"),
    get_view("frame", url="frame/<int:website_id>"),
    get_view("click"),
    get_view("advertisement", url="advertisement/<int:ad_id>"),
    get_view("website", url="website/<int:website_id>"),
    get_view("pause_advertisement", url="toggle/<int:ad_id>"),
    get_view("stripe_success"),
    get_view("stripe_connect"),
    get_view("stripe_elements"),
    get_view("stripe_setup_advertiser"),
    get_view("clicks_api")
]

websuggest/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path

from lib.helpers.routing import get_template_view, get_view

authurls = [
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns = [
    get_view("home", url=""),
    path("", include("app.urls")),
    path("site-admin/", admin.site.urls),
    path("accounts/", include(authurls)),
    get_template_view("beta_warning"),
    get_template_view("promotion"),
    get_template_view("publisher_docs")
]

app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from jsonfield import JSONField
from decimal import Decimal


class Website(models.Model):
    url = models.URLField()
    user = models.ForeignKey('Profile', on_delete=models.CASCADE)
    views = models.IntegerField(default=0)

    def __str__(self):
        return "({}) {}".format(self.id, self.url)


class Advertisement(models.Model):
    title = models.CharField(max_length=20)
    body = models.TextField(max_length=180)
    user = models.ForeignKey('Profile', on_delete=models.CASCADE)
    passed = models.BooleanField(default=False)
    target_url = models.URLField('URL to open when ad is clicked')
    paused = models.BooleanField(default=False)
    views = models.IntegerField(default=0)

    def __str__(self):
        if self.passed:
            return "({}) {} - {}".format(self.id, self.title, self.target_url)
        else:
            return "({}) {} - {} [AWAITING REVIEW]".format(
                self.id,
                self.title,
                self.target_url
            )

class Transaction(models.Model):
    def advertisement_charge_amount(self):
        result = Decimal(0)
        for adclick in self.advertisement_charge_adclick_set.all():
            result += adclick.price
        return result

class AdClick(models.Model):
    advertisement = models.ForeignKey(Advertisement, on_delete=models.CASCADE)
    website = models.ForeignKey(Website, on_delete=models.CASCADE)
    location = JSONField()
    datetime = models.DateTimeField()
    price = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    advertisement_charge_transaction = models.ForeignKey(Transaction,
        on_delete=models.SET_NULL, null=True, related_name='advertisement_charge_adclick_set')


class AdViewer(models.Model):
    ip = models.GenericIPAddressField()
    ad_clicks = models.IntegerField(default=0)
    last_click = models.DateTimeField()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    stripe_user_id = models.CharField(default="0", max_length=10000)
    stripe_customer = models.CharField(default="0", max_length=10000)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

app/views/AdvertisementView.py
from django.shortcuts import redirect, render

from lib.logic.total_balance import total_balance

from ..models import Advertisement


def AdvertisementView(request, ad_id):
    if request.user.is_authenticated:
        ad_object = Advertisement.objects.get(id=ad_id)
        if ad_object.user == request.user.profile:
            total_clicks = 0
            for click in ad_object.adclick_set.all():
                total_clicks += 1
            if total_clicks != 0:
                conversion_rate_raw = (total_clicks / ad_object.views) * 100
                # Round the conversion rate
                conversion_rate = round(conversion_rate_raw, 1)
            else:
                conversion_rate = 0
            return render(request, "advertisement_view.html", {
                "ad": ad_object,
                "total_clicks": total_clicks,
                "conversion_rate": conversion_rate,
                "total_balance": total_balance(request.user.profile)
            })
        else:
            return redirect("home")
    else:
        return redirect("home")

app/views/CreateAdvertisementView.py
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from ..forms import CreateAdvertisementForm


class CreateAdvertisementView(generic.FormView):
    template_name = 'create_advertisement.html'
    form_class = CreateAdvertisementForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        model_instance = form.save(commit=False)
        model_instance.user = self.request.user.profile
        model_instance.save()
        url = reverse("advertisement", kwargs={
            "ad_id": str(model_instance.id)
        })
        return redirect(url)

app/views/CreateWebsiteView.py
from django.shortcuts import redirect, render

from ..forms import CreateWebsiteForm


def CreateWebsiteView(request):
    if request.method == "POST":
        form = CreateWebsiteForm(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.user = request.user.profile
            model.save()
            return redirect("website", website_id=str(model.id))
    else:
        form = CreateWebsiteForm()
        return render(request, "create_website.html", {
            "form": form
        })

app/views/FrameView.py
from random import randint

from django.shortcuts import render
from django.views.decorators.clickjacking import xframe_options_exempt

from ..models import Advertisement, Website


@xframe_options_exempt
def FrameView(request, website_id):
    ads = Advertisement.objects.filter(passed=True, paused=False)
    count = ads.count()
    if count == 0:
        return render(request, "frame.html", {
            "object": {
                "title": "This could be your ad...",
                "body": "WebSuggest is a privacy-respecting, easy and simple way to advertise across an entire network of websites."
            },
            "website_id": None
        })
    random_object = ads[randint(0, count - 1)]
    website_object = Website.objects.get(id=website_id)
    website_object.views += 1
    website_object.save()
    random_object.views += 1
    random_object.save()
    return render(request, "frame.html", {
        "object": random_object,
        "website_id": website_object.id
    })

app/views/SignupView.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render

from ..forms import UserCreateForm


def SignupView(request):
    if request.method == "POST":
        form = UserCreateForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            form.save()
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
    else:
        form = UserCreateForm()
    return render(request, "signup.html", {
        "form": form
    })

app/views/StripeElementsView.py
from django.shortcuts import render

from websuggest import settings


def StripeElementsView(request):
    return render(request, "stripe_elements.html", {
        "stripe_public_key": settings.STRIPE_PUBLIC_KEY
    })

app/views/WebsiteView.py
from django.shortcuts import redirect, render

from lib.logic.conversion_rate import calc_conversion_rate
from lib.logic.total_balance import total_balance

from ..models import Website


def WebsiteView(request, website_id):
    if request.user.is_authenticated:
        website_object = Website.objects.get(id=website_id)
        if website_object.user == request.user.profile:
            total_clicks = 0
            for click in website_object.adclick_set.all():
                total_clicks += 1
            return render(request, "website_view.html", {
                "current_website": website_object,
                "total_clicks": total_clicks,
                "conversion_rate": calc_conversion_rate(total_clicks, website_object.views),
                "total_balance": total_balance(request.user.profile)
            })
        else:
            return redirect("home")
    else:
        return redirect("home")

templates/advertisement_view.html
{% extends "_base.html" %}
{% load mathfilters %}

{% block head %}
<script type="application/javascript" src="{% static "table.js" %}"></script>
<script type="application/javascript" src="{% static "frame.js" %}"></script>
{% endblock head %}

{% block content %}
<!--<div class="container">
    <a href="/" class="btn linkbtn" style="margin-top:0px"><i class="fas fa-long-arrow-alt-left"></i>&nbsp;Back Home</a>
    <table class="table">
        <tr>
            <th>ID</th>
            <td>{{ ad.id }}</td>
        </tr>
        <tr>
            <th>Title</th>
            <td>{{ ad.title }}</td>
        </tr>
        <tr>
            <th>Body</th>
            <td>{{ ad.body }}</td>
        </tr>
        <tr>
            <th>Destination URL</th>
            <td>{{ ad.target_url }}</td>
        </tr>
    </table>
    <div class="text-right">
        {% if ad.paused == False %}
            <a href="{% url "pause_advertisement" ad.id %}" class="btn btn-danger" id="pause" data-turbolinks="false">Pause Campaign</a>
        {% else %}
            <a href="{% url "pause_advertisement" ad.id %}" class="btn btn-danger" data-turbolinks="false">Resume Campaign</a>
        {% endif %}
    </div>
    <div style="padding:40px">
        <div class="row">
            <div class="col-4">Total Impressions</div>
            <div class="col-4">Total Clicks</div>
            <div class="col-4">Click Rate</div>
        </div>
        <div class="row">
            <div class="col-4"><h1 class="display-4">{{ ad.views }}</h1></div>
            <div class="col-4"><h1 class="display-4">{{ total_clicks }}</h1></div>
            <div class="col-4"><h1 class="display-4">{{ conversion_rate }}%</h1></div>
        </div>
    </div>
    <div id="click_table_container">
        <h3>Clicks</h3>
        <table class="table" id="click_table">
            <thead class="bg-primary">
                <tr>
                    <th>Time</th>
                    <th>IP Address</th>
                    <th>Referring Website</th>
                    <th>Price <i class="fas fa-question-circle" style="font-size:20px;color:#d9d9d9;cursor:default" id="tooltip"></i></th>
                </tr>
            </thead>
            {% for click in ad.adclick_set.all %}
                <tr>
                    <td><b>{{ click.datetime|date }} {{ click.datetime|time }}</b><br/>{{ click.datetime|timesince }} ago</td>
                    <td><span class="geoip">{{ click.ip }}</span></td>
                    <td>{{ click.website.url }}</td>
                    <td>${{ click.price }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>-->
<div class="Dashboard content">
    <div class="Dashboard-left-panel">
        <div class="Dashboard-top">
            <div class="Dashboard-label">Websites</div>
            <div class="Dashboard-sidebar-items">
                {% if user.profile.website_set.all %}
                    {% for website in user.profile.website_set.all %}
                        <a
                            class="Dashboard-sidebar-item nostyle"
                            href="{% url "website" website.id %}">
                            {{ website.url }}
                        </a>
                    {% endfor %}
                {% else %}
                    <div class="Dashboard-none">No websites</div>
                {% endif %}
            </div>
            {% if user.profile.stripe_user_id == "0" %}
                <a class="button-subtle Dashboard-add" href="{% url "stripe_connect" %}">Sign up to be a publisher</a>
            {% else %}
                <a class="button-subtle Dashboard-add" href="{% url "create_website" %}">Add new</a>
            {% endif %}
            <div class="Dashboard-label">Advertisements</div>
            <div class="Dashboard-sidebar-items">
                {% if user.profile.advertisement_set.all %}
                    {% for advertisement in user.profile.advertisement_set.all %}
                        <a
                            class="Dashboard-sidebar-item nostyle {% if advertisement == ad %}Dashboard-sidebar-item-active{% endif %}"
                            href="{% url "advertisement" advertisement.id %}">
                            {{ advertisement.title }}
                        </a>
                    {% endfor %}
                {% else %}
                    <div class="Dashboard-none">No advertisements</div>
                {% endif %}
            </div>
            {% if user.profile.stripe_customer == "0" %}
                <a class="button-subtle Dashboard-add" href="{% url "stripe_elements" %}">Sign up to be an advertiser</a>
            {% else %}
                <a class="button-subtle Dashboard-add" href="{% url "create_advertisement" %}">Add new</a>
            {% endif %}
        </div>
        <span class="Dashboard-bottom">
            <span class="Dashboard-balance-label">Total Balance</span>
            <div style="float: right">
                {% if total_balance >= 0 %}
                    ${{ total_balance }}
                {% else %}
                    -${{ total_balance|abs }}
                {% endif %}
            </div>
        </div>
        <div class="Dashboard-right-panel" style="display: flex; overflow: scroll">
            <div style="width: 60%">
                <div class="Dashboard-status">
                    Status
                    <div style="float: right">
                    {% if ad.passed == False %}
                        <span class="dot red"></span>
                        <span style="color: #cccccc" id="pending-review">Pending review</span>
                    {% elif ad.paused == True %}
                        <span class="dot red"></span>
                        <span style="color: #cccccc">Paused</span>
                        <a href="{% url "pause_advertisement" ad.id %}" class="Dashboard-toggle-button default-style" data-turbolinks="false">Unpause</a>
                    {% else %}
                        <span class="dot green"></span>
                        <span style="color: #cccccc">OK</span>
                        <a href="{% url "pause_advertisement" ad.id %}" class="Dashboard-toggle-button default-style"  id="pause_ad" data-turbolinks="false">Pause</a>
                    {% endif %}
                    </div>
                </div>
                <div id="vue-app" v-cloak>
                    <img src="{% static "img/spinner.gif" %}" class="loading" style="height: 100px; margin-left: auto; margin-right: auto; margin-top: 20px">
                    <div style="display: flex; width: 100%; justify-content: space-around; margin-top: 20px; text-align: center">
                        <div>
                            Total Views<br/>
                            <b><% api.total_views %></b>
                        </div>
                        <div>
                            Total Clicks<br/>
                            <b><% api.total_clicks %></b>
                        </div>
                        <div>
                            Click Rate<br/>
                            <b><% click_rate %></b>
                        </div>
                    </div>
                    <l-map style="width: 100%; height: 400px; margin-top: 20px" :min-zoom="1.3" :center="[45.522561, 10.110652]" :max-bounds="bounds" :bounds="bounds">
                        <l-tile-layer url="https://{s}.tile.osm.org/{z}/{x}/{y}.png" :no-wrap="true"></l-tile-layer>
                        <l-marker v-for="click in clicks_geolocated" :key="click.id" :lat-lng="[click.location.location.latitude, click.location.location.longitude]">
                            <l-popup>
                                <b>Location:&nbsp;</b><% click.location.city.names.en %>, <% click.location.country.names.en %>
                                <br/>
                                <b>Price:&nbsp;</b>$<% get_price(click) %>
                                <br/>
                                <b>Referring website:&nbsp;</b><a :href="click.website.url" target="_blank" rel="noopener"><% click.website.url %></a>
                            </l-popup>
                        </l-marker>
                    </l-map>
                    <line-chart :data="api.time_series" :download="true" :curve="false"></line-chart>
                </div>
            </div>
            <div class="panel" style="width: 40%; text-align: center; pointer-events: none">
                <b style="color: #808080; margin-bottom: 5px; display: inline-block">Preview</b>
                <div style="box-shadow:0px 0.5px 1px black;border-radius:4px; height: 300px; text-align: left">
                    <div class="Frame-body">
                        <div class="Frame-title">{{ ad.title }}</div>
                        <p>{{ ad.body }}</p>
                        <a
                            href=""
                            class="Frame-button default-style">
                            Learn More
                        </a>
                        <a href="" class="Frame-bottom-text default-style">
                            Advertising by WebSuggest
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="Dashboard-screen-size">
    <img src="{% static "img/android-phone.png" %}" class="illustration"></img>
    <p>Your screen is too small for WebSuggest Dashboard. Try accessing WebSuggest from a laptop or desktop computer.</p>
</div>
{% endblock %}

templates/beta_warning.html
{% extends "_base.html" %}

{% block content %}
<div class="container">
    <h1 class="display-4">WebSuggest is in early beta.</h1>
    <hr/>
    <p class="lead" style="margin-top:20px">You will likely see bugs and security vulnurabilities. Please do report them to <a href="mailto:bugs@websuggest.net">bugs@websuggest.net</a>. As it is in Beta, there is no payment system yet; all advertisements are free and no publishers will be paid. If you wish to contact me for a reason other than a bug report, you can email <a href="mailto:contact@websuggest.net">contact@websuggest.net</a>.</p>
</div>
{% endblock %}

templates/dashboard.html
{% extends "_base.html" %}
{% load mathfilters %}

{% block content %}
<div class="Dashboard content">
    <div class="Dashboard-left-panel">
        <div class="Dashboard-top">
            <div class="Dashboard-label">Websites</div>
            {% if user.profile.website_set.all %}
                {% for website in user.profile.website_set.all %}
                    <a
                        class="Dashboard-sidebar-item nostyle"
                        href="{% url "website" website.id %}"
                        >
                        {{ website.url }}
                    </a>
                {% endfor %}
            {% else %}
                <div class="Dashboard-none">No websites</div>
            {% endif %}
            {% if user.profile.stripe_user_id == "0" %}
                <a class="button-subtle Dashboard-add" href="{% url "stripe_connect" %}">Sign up to be a publisher</a>
            {% else %}
                <a class="button-subtle Dashboard-add" href="{% url "create_website" %}">Add new</a>
            {% endif %}
            <div class="Dashboard-label">Advertisements</div>
            {% if user.profile.advertisement_set.all %}
                {% for advertisement in user.profile.advertisement_set.all %}
                    <a class="Dashboard-sidebar-item nostyle" href="{% url "advertisement" advertisement.id %}">{{ advertisement.title }}</a>
                {% endfor %}
            {% else %}
                <div class="Dashboard-none">No advertisements</div>
            {% endif %}
            {% if user.profile.stripe_customer == "0" %}
                <a class="button-subtle Dashboard-add" href="{% url "stripe_elements" %}">Sign up to be an advertiser</a>
            {% else %}
                <a class="button-subtle Dashboard-add" href="{% url "create_advertisement" %}">Add new</a>
            {% endif %}
        </div>
        <span class="Dashboard-bottom">
            <span class="Dashboard-balance-label">Total Balance</span>
            <div style="float: right">
                {% if total_balance >= 0 %}
                    ${{ total_balance }}
                {% else %}
                    -${{ total_balance|abs }}
                {% endif %}
            </div>
        </div>
    <div class="Dashboard-right-panel">
        <div class="Dashboard-empty-state">
            <img src="{% static "img/ecology-globe.png" %}" class="illustration"></img>
            <b>You have no advertisements and no websites.</b>
            Use the panel on the left to create a new advertisement or website.
        </div>
    </div>
</div>
<div class="Dashboard-screen-size">
    <img src="{% static "img/android-phone.png" %}" class="illustration"></img>
    <p>Your screen is too small for WebSuggest Dashboard. Try accessing WebSuggest from a laptop or desktop computer.</p>
</div>
{% endblock %}

templates/onboard.html
{% extends "_base.html" %}

{% block content %}
<center class="content">
    <h1>Welcome to WebSuggest!</h1>
    <div class="halves">
        <a class="Onboard-halftile nostyle" href="{% url "stripe_connect" %}">
            <img src="{% static "img/monitor-cash-credit-card.png" %}" class="illustration"></img>
            <h2>Become a publisher</h2>
            <p>Put an ad on your website and start making money</p>
        </a>
        <a class="Onboard-halftile nostyle" href="{% url "stripe_elements" %}">
            <img src="{% static "img/success-goal-businessman.png" %}" class="illustration"></img>
            <h2>Become an advertiser</h2>
            <p>Promote your message on a growing network at low cost</p>
        </a>
    </div>
</center>
{% endblock %}

templates/website_view.html
{% extends "_base.html" %}
{% load mathfilters %}

{% block head %}
<script type="application/javascript" src="{% static "table.js" %}"></script>
{% endblock head %}

{% block content %}
<!--<div class="container">
    <a href="/" class="btn linkbtn" style="margin-top:0px"><i class="fas fa-long-arrow-alt-left"></i>&nbsp;Back Home</a>
    {% if total_clicks == 0 %}
        <div class="alert alert-primary" role="alert">
            <h3>All ready!</h3>
            <p>Just insert the following code on your page in the location you want the advertisement to be placed:</p>
            <kbd>
                &lt;iframe src=&quot;//beta.websuggest.net/app/frame/{{ website.id }}&quot; width=&quot;319&quot; height=&quot;248&quot; style=&quot;border:none;box-shadow:0px 0.5px 1px black;border-radius:4px&quot;&gt;&lt;/iframe&gt;
            </kbd>
            <br/><br/>
            <div>
                <a href="/publisher-docs" class="btn btn-outline-secondary">More Information&nbsp;<i class="fas fa-chevron-right"></i></a>
            </div>
        </div>
    {% endif %}
    <table class="table">
        <tr>
            <th>ID</th>
            <td>{{ website.id }}</td>
        <tr>
            <th>URL</th>
            <td>{{ website.url }}</td>
        </tr>
    </table>
    <div style="padding:40px">
        <div class="row">
            <div class="col-4"><small>Total Impressions</small></div>
            <div class="col-4"><small>Total Clicks</small></div>
            <div class="col-4"><small>Click Rate</small></div>
        </div>
        <div class="row">
            <div class="col-4"><h1 class="display-4">{{ website.views }}</h1></div>
            <div class="col-4"><h1 class="display-4">{{ total_clicks }}</h1></div>
            <div class="col-4"><h1 class="display-4">{{ conversion_rate }}%</h1></div>
        </div>
    </div>
    <div id="click_table_container">
        <h3>Clicks</h3>
        <table class="table" id="click_table">
            <thead class="bg-primary">
                <tr>
                    <th>Time</th>
                    <th>IP Address</th>
                    <th>Advertisement</th>
                    <th>Price<i class="fas fa-question-circle" style="font-size:20px;color:#d9d9d9;cursor:default" id="tooltip"></i></th>
                </tr>
            </thead>
            {% for click in website.adclick_set.all %}
                <tr>
                    <td><b>{{ click.datetime|date }} {{ click.datetime|time }}</b><br/>{{ click.datetime|timesince }} ago</td>
                    <td><span class="geoip">{{ click.ip }}</span></td>
                    <td>
                        <p><b>{{ click.advertisement.title }} ({{ click.advertisement.target_url }})</b></p>
                        <p>{{ click.advertisement.body|truncatechars:60 }}<p>
                    </td>
                    <td>${{ click.price|mul:0.7 }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>-->
<div class="Dashboard content">
    <span class="Dashboard-left-panel">
        <div class="Dashboard-top">
            <div class="Dashboard-label">Websites</div>
            <div class="Dashboard-sidebar-items">
            {% if user.profile.website_set.all %}
                {% for website in user.profile.website_set.all %}
                    <a
                        class="Dashboard-sidebar-item nostyle {% if website == current_website %}Dashboard-sidebar-item-active{% endif %}"
                        href="{% url "website" website.id %}"
                        >
                        {{ website.url }}
                    </a>
                {% endfor %}
            {% else %}
                <div class="Dashboard-none">No websites</div>
            {% endif %}
            </div>
            {% if user.profile.stripe_user_id == "0" %}
                <a class="button-subtle Dashboard-add" href="{% url "stripe_connect" %}">Sign up to be a publisher</a>
            {% else %}
                <a class="button-subtle Dashboard-add" href="{% url "create_website" %}">Add new</a>
            {% endif %}
            <div class="Dashboard-label">Advertisements</div>
            <div class="Dashboard-sidebar-items">
            {% if user.profile.advertisement_set.all %}
                {% for advertisement in user.profile.advertisement_set.all %}
                    <a class="Dashboard-sidebar-item nostyle" href="{% url "advertisement" advertisement.id %}">{{ advertisement.title }}</a>
                {% endfor %}
            {% else %}
                <div class="Dashboard-none">No advertisements</div>
            {% endif %}
            </div>
            {% if user.profile.stripe_customer == "0" %}
                <a class="button-subtle Dashboard-add" href="{% url "stripe_elements" %}">Sign up to be an advertiser</a>
            {% else %}
                <a class="button-subtle Dashboard-add" href="{% url "create_advertisement" %}">Add new</a>
            {% endif %}
        </div>
        <div class="Dashboard-bottom">
            <span class="Dashboard-balance-label">Total Balance</span>
            <div style="float: right">
                {% if total_balance >= 0 %}
                    ${{ total_balance }}
                {% else %}
                    -${{ total_balance|abs }}
                {% endif %}
            </div>
        </div>
    </span>
    <div class="Dashboard-right-panel">
        {% if current_website.views == 0 %}
            <div class="Dashboard-alert">
                <h3>All ready!</h3>
                <p>Just insert the following code on your page in the location you want the advertisement to be placed:</p>
                <div style="display:flex">
                    <code id="copy" class="Dashboard-code">
                        &lt;iframe src=&quot;{% if request.is_secure %}https{% else %}http{% endif %}://{{ request.META.HTTP_HOST }}/frame/{{ current_website.id }}&quot; width=&quot;320&quot; height=&quot;240&quot; style=&quot;border:none;box-shadow:0px 0.5px 1px black;border-radius:4px&quot;&gt;&lt;/iframe&gt;
                    </code>
                    <button id="clipboard-trigger" data-clipboard-target="#copy" style="font-size: 1.5em;cursor:pointer">📋</button>
                </div>
            </div>
        {% endif %}
        <div id="vue-app" v-cloak>
            <img src="{% static "img/spinner.gif" %}" class="loading" style="height: 100px; margin-left: auto; margin-right: auto; margin-top: 20px">
            <div style="display: flex; width: 100%; justify-content: space-around; margin-top: 20px; text-align: center">
                <div>
                    Total Views<br/>
                    <b><% api.total_views %></b>
                </div>
                <div>
                    Total Clicks<br/>
                    <b><% api.total_clicks %></b>
                </div>
                <div>
                    Click Rate<br/>
                    <b><% click_rate %></b>
                </div>
            </div>
            <l-map style="width: 100%; height: 400px; margin-top: 20px" :min-zoom="1.3" :center="[45.522561, 10.110652]" :max-bounds="bounds" :bounds="bounds">
                <l-tile-layer url="https://{s}.tile.osm.org/{z}/{x}/{y}.png" :no-wrap="true"></l-tile-layer>
                <l-marker v-for="click in clicks_geolocated" :key="click.id" :lat-lng="[click.location.location.latitude, click.location.location.longitude]">
                    <l-popup>
                        <b>Location:&nbsp;</b><% click.location.city.names.en %>, <% click.location.country.names.en %>
                        <br/>
                        <b>Price:&nbsp;</b>$<% get_price(click) %>
                        <br/>
                        <b>Referring website:&nbsp;</b><a :href="click.website.url" target="_blank" rel="noopener"><% click.website.url %></a>
                    </l-popup>
                </l-marker>
            </l-map>
            <line-chart :data="api.time_series" :download="true" :curve="false"></line-chart>
    </div>
</div>
<div class="Dashboard-screen-size">
    <img src="{% static "img/android-phone.png" %}" class="illustration"></img>
    <p>Your screen is too small for WebSuggest Dashboard. Try accessing WebSuggest from a laptop or desktop computer.</p>
</div>
{% endblock %}